---
  defaultBaseImageVersion: latest
  properties:
  - name: API_KEY
    value: ${API_KEY}
    type: secure
  - name: PROD_CLUSTER_NAME
    value: ${PROD_CLUSTER_NAME}
    type: text
  - name: PROD_REGION_ID
    value: ${PROD_REGION_ID}
    type: text
  stages:
  - name: FETCH
    inputs:
    - type: git
      branch: master
      service: ${GIT_REPO}    
    triggers:
    - type: commit
    properties:
    - name: IMAGE_NAME
      value: ${APP_NAME}
      type: text
    jobs:
    - name: Fetch code
      type: builder
      artifact_dir: ''
      build_type: shell
      script: |+
        #!/bin/bash
        # set -x
  
        # Git repo cloned at $WORKING_DIR, copy into $ARCHIVE_DIR
        mkdir -p $ARCHIVE_DIR
        cp -R -n ./ $ARCHIVE_DIR/ || true
  
        # Record git info
        echo "GIT_URL=${GIT_URL}" >> $ARCHIVE_DIR/build.properties
        echo "GIT_BRANCH=${GIT_BRANCH}" >> $ARCHIVE_DIR/build.properties
        echo "GIT_COMMIT=${GIT_COMMIT}" >> $ARCHIVE_DIR/build.properties
        echo "SOURCE_BUILD_NUMBER=${BUILD_NUMBER}" >> $ARCHIVE_DIR/build.properties
        cat $ARCHIVE_DIR/build.properties
  - name: DEPLOY_PREREQS
    properties:
    - name: buildprops
      value: build.properties
      type: file
    - name: DOCKER_ROOT
      value: .
      type: text
    - name: DOCKER_FILE
      value: Dockerfile
      type: text
    - name: PIPELINE_IMAGE_URL
      value: undefined
      type: text
    inputs:
    - type: job
      stage: FETCH
      job: Fetch code
    triggers:
    - type: stage
    jobs:
    - name: Deploy Kafka
      type: deployer
      build_type: kubernetes
      target:
        region_id: ${PROD_REGION_ID}
        api_key: ${API_KEY}
        kubernetes_cluster: ${PROD_CLUSTER_NAME}
      script: |-
        #!/bin/bash
        kubectl create namespace kafka || true
        curl -L https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.15.0/strimzi-cluster-operator-0.15.0.yaml \
          | sed 's/namespace: .*/namespace: kafka/' \
          | kubectl apply -f - -n kafka || true
        cd reactive
        kubectl apply -f /scripts/kafka-cluster.yaml -n kafka || true
    - name: Deploy Kafka
      type: deployer
      build_type: kubernetes
      target:
        region_id: ${PROD_REGION_ID}
        api_key: ${API_KEY}
        kubernetes_cluster: ${PROD_CLUSTER_NAME}
      script: |-
        #!/bin/bash
        echo start
  - name: DEPLOY
    properties:
    - name: buildprops
      value: build.properties
      type: file
    inputs:
    - type: job
      stage: FETCH
      job: Fetch code
    triggers:
    - type: stage
    jobs:
    - name: Deploy to OpenShift
      type: deployer
      build_type: kubernetes
      target:
        region_id: ${PROD_REGION_ID}
        api_key: ${API_KEY}
        kubernetes_cluster: ${PROD_CLUSTER_NAME}
      script: |+
        #!/bin/bash  
        echo end

